source 'http://rubygems.org'

gem 'rails', '3.2.19'
gem 'jquery-rails'
gem 'sqlite3'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end
group :development, :test do
  gem "database_cleaner"
  gem 'rspec-rails'
  gem 'debugger'
  gem 'factory_girl_rails'
end
