
development:
  database: simulator_development
  adapter: postgresql
  encoding: unicode
  pool: 5

test:
  database: simulator_test
  adapter: postgresql
  encoding: unicode
  pool: 5

production:
  database: simulator_production
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: simulator
  password: password
